sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: EdizswK5nxDZD3s2JY8xjZbiW1LMOUKJUjILr9ASeCuVK31YsBf/4Hd3XoLLV3hx/7V5taUwGOKhj/XCh31J8KlIrLutBMNZOtG5C35N+vCpLV/xSDiXyAVdIsLC07Dih3GNNU81N/G7zVSkhIKFbt/ErB9anE57HDyvnAldUaenoOSFtmrFeXXKWjDlFijlmhFN+pEfCLFZtxtUKI8LDJDySHePM59POcZ1ufnk+NP2sKFmcR0VjEM769cLlcI2qpC11nGCCLhbloc08ZuLFzpTRF5VndTSmxQcEKC9prVBesvtWLqJOTQEyTWfc/lSsTztvdpDQ1/xRD4NkybOvZZDThmmuA6Zgh7qijR3d8oIIa8qha/zQphrYnw0TU3xZus9rnJbNdgpiZOgOvEPDzwNodbc/mmdo8iyQuwBjZb7LOVwz2QMgckz2L7BbeS/9GuJFwNaJCrwuADWRkRZuGqKFTSjPF/vaV/xuw01Mh3fkn295YcicOYZh08qdJiyfFAxRcL+pfzYZRpEI4Mly9BpbDL9H+6EKkVx0DsJ4Gon/+pSoyNOwu65omlsKV8g4DDHuntxd0yL+hytll4kd9/lJBpxPibgKhmXSHl5nkiyGLiu1Sb7YW2Lq2PyEtGYrKPC79/dYtVpd+XM/CoftWBPBn+kmFukK+caaOtbPJQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Young-Carthaginian--A-Story-of-The-Times-of-Hannibal_5128
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy